version: '3.8'

services:
  backend:
    build: ./backend
    container_name: fastapi_service
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: streamlit_ui
    ports:
      - "8501:8501"
    depends_on:
      - backend
